@ctype = Content-Type
@appjson = application/json

@host = http://localhost:8000
@version = HTTP/1.1

@token = secretkeypleaseecret


POST {{host}}/producers {{version}}
Content-Type: application/json

{
    "name": "customers",
    "location": "http://locahost:8000",
    "passphrase": "secretkeypleaseecret"
}

###

POST {{host}}/events {{version}}
Content-Type: {{appjson}}
Authorization: bearer {{token}}

{
    "event": "customers.v1.products.created",
    "producer": "customers",
    "schemata": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://example.com/product.schema.json",
        "title": "Product",
        "description": "A product from Acme's catalog",
        "type": "object",
        "properties": {
            "product_id": {
                "description": "The unique identifier for a product",
                "type": "integer"
            }
        },
        "required": [ "product_id" ]
    }
}

###

POST {{host}}/actions {{version}}
Content-Type: {{appjson}}
Authorization: bearer {{token}}

{
    "event": "identities.v1.identities.created",
    "deduper": 1000,
    "payload": {
        "id": 114
    }
}

###

POST {{host}}/subscribers {{version}}
Content-Type: {{appjson}}

{
    "event": "customers.v1.products.created",
    "producer": "notifications",
    "endpoint": "/h1/customer-created",
    "description": "when customer is created handle it in orders services"
}

###


# GET Methods


GET {{host}}/producers {{version}}
###

GET {{host}}/events {{version}}
###

GET {{host}}/actions {{version}}
###

GET {{host}}/subscribers {{version}}
Accept: {{appjson}}
###


GET {{host}}/gists {{version}}
###


# PUT METHODS

PUT {{host}}/v1/producers/customers
Content-Type: {{appjson}}

{
    "location": "http://0.0.0.0:8000",
    "passphrase": "secretkeypleaseecret"
}
